parameters:
  - name: env
    displayName: 'Environment'
    default: prod
    type: string
    values:
      - dev
      - prod

  - name: browser
    displayName: 'Browser'
    default: chrome
    type: string
    values:
      - chrome
      - firefox
      - edge
      - electron

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run test-${{parameters.env}} -- --browser ${{parameters.browser}}
    displayName: 'Run tests'
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/cypress/results/junitreport.xml'
    displayName: 'Publish report'

  - task: publishhtmlreport@1
    inputs:
      htmlType: 'genericHTML'
      htmlPath: '**/cypress/results/index.html'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'cypress/results/output.txt'
      ArtifactName: 'output'
      publishLocation: 'Container'
  